jobs:
  include:
    - stage: "Tests"
      name: "unit Tests"
      language: node_js
      node: node
      cache:
        directories:
          - node_modules
      before_install: 
        - nvm install node
      install: yarn
      script: 
        - yarn prod:web
        - yarn test

    - stage: "android"
      name: "android"
      # if: branch = staging
      language: android
      jdk: oraclejdk8
      before_install: 
        - nvm install node
      #  - mkdir "$ANDROID_HOME/licenses" || true
       # - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55\nd56f5187479451eabf01fb78af6dfcb131a6481e" > "$ANDROID_HOME/licenses/android-sdk-license"
       # - echo -e "\n504667f4c0de7af1a06de9f4b1727b84351f2910" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
        - chmod +x ./android/gradlew
        - ls -l ./android/app
        # - openssl aes-256-cbc -K $encrypted_e928a807721e_key -iv $encrypted_e928a807721e_iv -in ./android/app/rnre.keystore.enc -out ./android/app/rnre.keystore -d
        # - openssl aes-256-cbc -K $encrypted_e928a807721e_key -iv $encrypted_e928a807721e_iv -in ./android/app/secrets.tar.enc -out ./android/app/secrets.tar -d
        # - openssl aes-256-cbc -K $encrypted_dc0bfcc22e44_key -iv $encrypted_dc0bfcc22e44_iv -in ./secrets/secrets.tar.enc -out ./secrets/secrets.tar -d
        - openssl aes-256-cbc -K $encrypted_0822e1e3bd37_key -iv $encrypted_0822e1e3bd37_iv -in ./secrets/secrets.tar.enc -out ./secrets/secrets.tar -d
        # - chmod +x ./android/app/secrets.tar
        - cd ./secrets
        - ls -l
        - tar xvf secrets.tar
        - ls -l
        - cd ../android
        - yes | sdkmanager "platforms;android-27"
        - gem install fastlane --no-document --quiet
        - cd ..
      install: yarn
      android:
        components:
          - tools
          - platform-tools
          - android-26
          - extra-google-m2repository
          - extra-google-google-play-services
        licenses:
          - 'android-sdk-license-.+'
      before_cache:
        - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
        - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
      cache:
        directories:
          - $HOME/.gradle/caches/
          - $HOME/.gradle/wrapper/
          - $HOME/.android/build-cache
      script: 
        - cd ./android
        - ./gradlew clean
        - fastlane beta